#!/usr/bin/env bash
# Copies what Prilog needs from this repo into the backend:
#   schema/, packages/, dist/, tools/pex.mjs, tools/pex.d.ts  →  <backend>/src/modules/schulsystem/pex/
# and writes pex/VERSION (git describe of this repo) so the backend knows what it runs.
#
# Usage: tools/sync-to-prilog.sh /home/lee/prilog-backend-api
# The target directory is replaced wholesale; it is generated, never edited by hand.
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND="${1:?usage: sync-to-prilog.sh <prilog-backend-api path>}"
MOD="$BACKEND/src/modules/schulsystem"
[ -d "$MOD" ] || { echo "not a Prilog backend (missing $MOD)"; exit 1; }

python3 "$HERE/tools/validate.py" >/dev/null || { echo "validate.py failed – not syncing"; exit 1; }
python3 "$HERE/tools/build.py" --check >/dev/null || { echo "dist/ is stale – run tools/build.py first"; exit 1; }

TARGET="$MOD/pex"
rm -rf "$TARGET"
mkdir -p "$TARGET/tools"
cp -r "$HERE/schema" "$HERE/packages" "$HERE/dist" "$TARGET/"
cp "$HERE/tools/pex.mjs" "$HERE/tools/pex.d.ts" "$TARGET/tools/"
( cd "$HERE" && git describe --always --dirty --tags 2>/dev/null || echo unknown ) > "$TARGET/VERSION"
cat > "$TARGET/README.md" <<'MD'
Generated by tools/sync-to-prilog.sh from https://github.com/brasilspace/PEX-Prilog-Education-Exchange
Do not edit here. Corrections go to the PEX repo; then sync again. VERSION says which state this is.
MD
echo "synced PEX $(cat "$TARGET/VERSION") → $TARGET"
find "$TARGET" -type f | wc -l | xargs echo "files:"
